version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: housing-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:newpassword@db/housing
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: newpassword
      POSTGRES_DB: housing
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
